FROM openjdk:17-jdk-slim
WORKDIR /app

ARG DBHOST
ARG DBPORT
ARG DB
ARG USERNAME
ARG DBPASSWORD
ARG JWTSECRET
ARG JWTISSUER
ARG DNF
ARG CYPHERS

ENV DBHOST=${DBHOST}
ENV DBPORT=${DBPORT}
ENV DB=${DB}
ENV USERNAME=${USERNAME}
ENV DBPASSWORD=${DBPASSWORD}
ENV JWTSECRET=${JWTSECRET}
ENV JWTISSUER=${JWTISSUER}
ENV DNF=${DNF}
ENV CYPHERS=${CYPHERS}

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN chmod +x ./gradlew
RUN ./gradlew clean bootJar

EXPOSE 8081
ENTRYPOINT ["java","-Dspring.profiles.active=dev", "-jar", "build/libs/board-api.jar"]